apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-demo-app
  namespace: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops-demo-app
  template:
    metadata:
      labels:
        app: devsecops-demo-app
    spec:
      containers:
        - name: devsecops-demo-app
          image: registry.jenkins.svc.cluster.local:5000/devsecops-demo-app:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000