apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops-demo-app
  template:
    metadata:
      labels:
        app: devsecops-demo-app
    spec:
      containers:
        - name: devsecops-demo-app
          image: devsecops-demo-app:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 5000